name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.PROD_DOCKER_USER }}
        password: ${{ secrets.PROD_DOCKER_PASSWORD }}
        login-server: https://${{ secrets.PROD_DOCKER_REGISTRY }}

    - name: Build Docker Image
      working-directory: ./
      run: docker build -f ./Dockerfile -t ${{ secrets.PROD_DOCKER_REGISTRY }}/orchard-core-medium-blog:latest .

    - name: Push Image
      working-directory: ./ 
      run: docker push ${{ secrets.PROD_DOCKER_REGISTRY }}/orchard-core-medium-blog:latest
